name:                haskell-ffprobe
version:             0.1.0.0
github:              "Arthi-chaud/haskell-ffprobe"
license:             BSD-3-Clause
author:              "Arthi-chaud"
copyright:           "2024 Arthi-chaud"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/Arthi-chaud/haskell-ffprobe#readme>

dependencies:
- base >= 4.7 && < 5
- process

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - process

tests:
  haskell-ffprobe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-ffprobe
